app: hypercorn app --reload --debug --bind app.local.gd:$PORT --access-logfile - --error-logfile - --log-level DEBUG
api: hypercorn api --reload --debug --bind api.local.gd:$PORT --access-logfile - --error-logfile - --log-level DEBUG
